/* Generated by build.js from environment variables. Do not edit. */
window.BUILDLIST_CONFIG = {
  "supabaseUrl": "",
  "supabaseAnonKey": "",
  "gaMeasurementId": "",
  "gaPropertyId": "",
  "featureReviews": "",
  "phone": "",
  "whatsapp": "",
  "email": "hello@buildlist.com",
  "adsEmail": "advertising@buildlist.com",
  "address": "",
  "ursb": "",
  "tin": ""
};
